language: lisp
sudo: required

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    #- LISP=ccl
    #- LISP=clisp
    #- LISP=cmucl
    #- LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl
    - env: LISP=allegro

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh  
  - git clone --depth=1 git@github.com:bendudson/array-operations.git ~/lisp/array-operations
    
script:
  - cl -e '(ql:quickload :array-operations)
           (ql:quickload :array-operations-tests)
           (array-operations-tests:run)'
  